version: '3.7'

services:
  recipebot:
    image: recipebot_server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
        - 4000:80
        - 4001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: ${sqlServer} 
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '1433:1433'  
    expose:  
      - 1433  